Update clone-repo-and-add-secret-not-git.yml

diff --git a/clone-repo-and-add-secret-not-git.yml b/clone-repo-and-add-secret-not-git.yml
--- a/clone-repo-and-add-secret-not-git.yml
+++ b/clone-repo-and-add-secret-not-git.yml
@@ -153,3 +153,26 @@ jobs:
             echo "✅ Set Permissions for ${repo}"
             sleep 5
           done
+      - name: Trigger Workflow on Each Repository
+        run: |
+          IFS=' ' read -r -a new_names <<< "$new_names"
+
+          for repo in "${new_names[@]}"; do
+            echo "Triggering workflow for ${repo}..."
+
+            RESPONSE=$(curl -s -L -X POST -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
+              -H "Accept: application/vnd.github+json" \
+              https://api.github.com/repos/${GIT_NAME}/${repo}/actions/workflows/main.yml/dispatches \
+              -d '{"ref": "main"}')
+
+            HTTP_STATUS=$(echo "$RESPONSE" | jq -r '.message // empty')
+
+            if [[ "$HTTP_STATUS" != "" ]]; then
+              echo "❌ Failed to trigger workflow for ${repo}: $HTTP_STATUS"
+              exit 1
+            fi
+
+            echo "✅ Triggered workflow for ${repo}"
+            sleep 5
+          done
+
