Update clone-repo-and-add-secret-not-git.yml

diff --git a/clone-repo-and-add-secret-not-git.yml b/clone-repo-and-add-secret-not-git.yml
--- a/clone-repo-and-add-secret-not-git.yml
+++ b/clone-repo-and-add-secret-not-git.yml
@@ -127,3 +127,25 @@ jobs:
 
             echo "✅ Added secret to ${repo}"
           done
+                - name: Set Workflow Permissions to Read & Write
+        run: |
+          IFS=' ' read -r -a new_names <<< "$new_names"
+
+          for repo in "${new_names[@]}"; do
+            echo "Setting workflow permissions for ${repo}..."
+
+            RESPONSE=$(curl -s -L -X PUT -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/repos/${GIT_NAME}/${repo}/actions/permissions \
+              -d '{"default_workflow_permissions": "write", "can_approve_pull_request_reviews": false}')
+
+            if [[ "$RESPONSE" == *"write"* ]]; then
+              echo "✅ Successfully set workflow permissions for ${repo}"
+            else
+              echo "❌ Failed to set workflow permissions for ${repo}"
+              exit 1
+            fi
+
+            sleep 3
+          done
